### ISSUE TITLE
Request for License Change to GPLv2

### ISSUE THREAD

**Issue by harshu4** [Openmesh-Network/xnode-admin#5]
**Request:**
We kindly request all contributors to respond to this issue with one of the following:
- **ack**: I approve the license change to GPv2.
- **nack**: I do not approve the license change to GPLv2.

**Response Deadline:**
Please respond by 14/07/2024. If no response is received by then, it will be assumed that you approve ("ack") of the license change.

Thank you for your attention to this matter.

cc: @justinlynn @j-openmesh @dowdt @harrys522

**Comment by harrys522** [comment]
Not acknowledged, waiting for other author's input but I prefer MIT for this repository.

https://github.com/Openmesh-Network/xnode-admin/pull/6

**Comment by dowdt** [comment]
nack, as well going with MIT #6
